name: Bump Version

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version type to bump'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Get current version
        id: current_version
        run: |
          CURRENT_VERSION=$(grep 'TAMEDIA_TOOLS_VERSION=' scripts/common.sh | cut -d'"' -f2)
          echo "current=${CURRENT_VERSION}" >> $GITHUB_OUTPUT

      - name: Calculate new version
        id: new_version
        run: |
          CURRENT="${{ steps.current_version.outputs.current }}"
          IFS='.' read -r -a VERSION_PARTS <<< "$CURRENT"
          
          MAJOR="${VERSION_PARTS[0]}"
          MINOR="${VERSION_PARTS[1]}"
          PATCH="${VERSION_PARTS[2]}"
          
          case "${{ github.event.inputs.version_type }}" in
            major)
              MAJOR=$((MAJOR + 1))
              MINOR=0
              PATCH=0
              ;;
            minor)
              MINOR=$((MINOR + 1))
              PATCH=0
              ;;
            patch)
              PATCH=$((PATCH + 1))
              ;;
          esac
          
          NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"
          echo "new=${NEW_VERSION}" >> $GITHUB_OUTPUT

      - name: Update version in files
        run: |
          NEW_VERSION="${{ steps.new_version.outputs.new }}"
          
          # Update common.sh
          sed -i "s/TAMEDIA_TOOLS_VERSION=\".*\"/TAMEDIA_TOOLS_VERSION=\"${NEW_VERSION}\"/" scripts/common.sh
          
          # Update Formula files
          for formula in Formula/*.rb; do
            sed -i "s/version \".*\"/version \"${NEW_VERSION}\"/" "$formula"
          done
          
          # Update README if it contains version
          if grep -q "v[0-9]\+\.[0-9]\+\.[0-9]\+" README.md; then
            sed -i "s/v[0-9]\+\.[0-9]\+\.[0-9]\+/v${NEW_VERSION}/g" README.md
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: bump version to ${{ steps.new_version.outputs.new }}"
          title: "Bump version to ${{ steps.new_version.outputs.new }}"
          body: |
            Automated version bump from ${{ steps.current_version.outputs.current }} to ${{ steps.new_version.outputs.new }}
            
            Version type: ${{ github.event.inputs.version_type }}
            
            After merging this PR, create a new release with tag `v${{ steps.new_version.outputs.new }}`
          branch: bump-version-${{ steps.new_version.outputs.new }}
          delete-branch: true