name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "version_num=${VERSION#v}" >> $GITHUB_OUTPUT

      - name: Build release artifacts
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          RELEASE_DIR="tamedia-tools-${VERSION}"

          # Create release directory
          mkdir -p "${RELEASE_DIR}"

          # Copy essential files
          cp -r tools scripts completion README.md LICENSE "${RELEASE_DIR}/"

          # Create tarball
          tar -czf "${RELEASE_DIR}.tar.gz" "${RELEASE_DIR}"

          # Calculate SHA256
          SHA256=$(shasum -a 256 "${RELEASE_DIR}.tar.gz" | awk '{print $1}')
          echo "SHA256=${SHA256}" >> $GITHUB_ENV
          echo "TARBALL=${RELEASE_DIR}.tar.gz" >> $GITHUB_ENV

          # Generate SHA256 file
          echo "${SHA256}  ${RELEASE_DIR}.tar.gz" > SHA256SUMS.txt


      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ steps.version.outputs.version }}
          body: |
            ## tamedia-tools ${{ steps.version.outputs.version }}

            AWS service tunneling tool for Kubernetes, designed for Tamedia's infrastructure workflows.

            ### ✨ Features
            - **Secure tunneling** to AWS services through Kubernetes pods
            - **Interactive selection** for DocumentDB, RDS (PostgreSQL/MySQL), ElastiCache (Redis/Valkey)
            - **Automatic credentials** integration with AWS Secrets Manager
            - **Smart port management** with automatic port conflict resolution
            - **Enhanced secret discovery** with fzf fuzzy finding support
            - **Clean exit handling** with automatic resource cleanup prompts

            ### 📦 Installation

            #### Homebrew (recommended)
            ```bash
            brew tap dnd-it/tamedia-tools
            brew install tamedia-tools
            ```

            #### Direct installation
            ```bash
            curl -sSL https://raw.githubusercontent.com/dnd-it/tamedia-tools/main/scripts/install.sh | bash
            ```

            ### 📋 Requirements
            - AWS CLI configured with appropriate permissions
            - kubectl configured for your Kubernetes cluster
            - jq for JSON processing
            - fzf (optional, for enhanced secret search)

            ### 🚀 Quick Start
            After installation, run:
            ```bash
            tamedia-tunnel
            ```

            The tool will guide you through service selection, instance selection, and automatic tunnel setup.

            ---

            **Full Changelog**: https://github.com/dnd-it/tamedia-tools/compare/v0.0.0...${{ steps.version.outputs.version }}
          files: |
            ${{ env.TARBALL }}
            SHA256SUMS.txt
          draft: false
          prerelease: false